
// This file has been generated by the GUI designer. Do not modify.
namespace omarkhd.Gymk
{
	public partial class ClientsWindow
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.HBox hbox6;

		private global::Gtk.HBox hbox7;

		private global::Gtk.VBox vbox4;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label2;

		private global::Gtk.Entry SearchEntry;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView ClientsNodeView;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox8;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.HBox hbox17;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label label12;

		private global::Gtk.Label IdLabel;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Label label14;

		private global::Gtk.Entry NameEntry;

		private global::Gtk.VBox vbox10;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Label label15;

		private global::Gtk.Entry SurnameEntry;

		private global::Gtk.HBox hbox20;

		private global::Gtk.Label label16;

		private global::Gtk.Entry AddressEntry;

		private global::Gtk.VBox vbox12;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Label label17;

		private global::Gtk.Entry PhoneEntry;

		private global::Gtk.HBox hbox23;

		private global::Gtk.Label label19;

		private global::Gtk.Entry EmailEntry;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Button EditButton;

		private global::Gtk.Button DeleteButton;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Button OkButton;

		private global::Gtk.Button CancelButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget omarkhd.Gymk.ClientsWindow
			this.Name = "omarkhd.Gymk.ClientsWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Clientes");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(6));
			// Container child omarkhd.Gymk.ClientsWindow.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(1));
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox2.Add (this.fixed1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("/");
			this.hbox8.Add (this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.SearchEntry = new global::Gtk.Entry ();
			this.SearchEntry.WidthRequest = 100;
			this.SearchEntry.CanFocus = true;
			this.SearchEntry.Name = "SearchEntry";
			this.SearchEntry.IsEditable = true;
			this.SearchEntry.InvisibleChar = '●';
			this.hbox8.Add (this.SearchEntry);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.SearchEntry]));
			w3.Position = 1;
			this.vbox4.Add (this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 100;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.ClientsNodeView = new global::Gtk.NodeView ();
			this.ClientsNodeView.CanFocus = true;
			this.ClientsNodeView.Name = "ClientsNodeView";
			this.GtkScrolledWindow.Add (this.ClientsNodeView);
			this.vbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow]));
			w6.Position = 1;
			this.hbox7.Add (this.vbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox4]));
			w7.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.WidthRequest = 270;
			this.frame1.Name = "frame1";
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.vbox11.Add (this.fixed5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.fixed5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox ();
			this.hbox17.HeightRequest = 20;
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox ();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Número de cliente: ");
			this.hbox22.Add (this.label12);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label12]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.IdLabel = new global::Gtk.Label ();
			this.IdLabel.Name = "IdLabel";
			this.IdLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0000");
			this.hbox22.Add (this.IdLabel);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.IdLabel]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox17.Add (this.hbox22);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.hbox22]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox11.Add (this.hbox17);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox17]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox ();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.WidthRequest = 60;
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.label14.Wrap = true;
			this.hbox18.Add (this.label14);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.label14]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.NameEntry = new global::Gtk.Entry ();
			this.NameEntry.CanFocus = true;
			this.NameEntry.Name = "NameEntry";
			this.NameEntry.IsEditable = true;
			this.NameEntry.InvisibleChar = '●';
			this.hbox18.Add (this.NameEntry);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.NameEntry]));
			w14.Position = 1;
			w14.Padding = ((uint)(3));
			this.vbox11.Add (this.hbox18);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox18]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox8.Add (this.vbox11);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox11]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox ();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.WidthRequest = 60;
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellido:");
			this.label15.Wrap = true;
			this.hbox19.Add (this.label15);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.label15]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.SurnameEntry = new global::Gtk.Entry ();
			this.SurnameEntry.CanFocus = true;
			this.SurnameEntry.Name = "SurnameEntry";
			this.SurnameEntry.IsEditable = true;
			this.SurnameEntry.InvisibleChar = '●';
			this.hbox19.Add (this.SurnameEntry);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.SurnameEntry]));
			w18.Position = 1;
			w18.Padding = ((uint)(3));
			this.vbox10.Add (this.hbox19);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox19]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox ();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.WidthRequest = 60;
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Dirección:");
			this.label16.Wrap = true;
			this.hbox20.Add (this.label16);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.label16]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox20.Gtk.Box+BoxChild
			this.AddressEntry = new global::Gtk.Entry ();
			this.AddressEntry.CanFocus = true;
			this.AddressEntry.Name = "AddressEntry";
			this.AddressEntry.IsEditable = true;
			this.AddressEntry.InvisibleChar = '●';
			this.hbox20.Add (this.AddressEntry);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.AddressEntry]));
			w21.Position = 1;
			w21.Padding = ((uint)(3));
			this.vbox10.Add (this.hbox20);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.hbox20]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox ();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.WidthRequest = 60;
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono:");
			this.label17.Wrap = true;
			this.hbox21.Add (this.label17);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label17]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.PhoneEntry = new global::Gtk.Entry ();
			this.PhoneEntry.CanFocus = true;
			this.PhoneEntry.Name = "PhoneEntry";
			this.PhoneEntry.IsEditable = true;
			this.PhoneEntry.InvisibleChar = '●';
			this.hbox21.Add (this.PhoneEntry);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.PhoneEntry]));
			w24.Position = 1;
			w24.Padding = ((uint)(3));
			this.vbox12.Add (this.hbox21);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox21]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox ();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label ();
			this.label19.WidthRequest = 60;
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Email:");
			this.label19.Wrap = true;
			this.hbox23.Add (this.label19);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.label19]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.EmailEntry = new global::Gtk.Entry ();
			this.EmailEntry.CanFocus = true;
			this.EmailEntry.Name = "EmailEntry";
			this.EmailEntry.IsEditable = true;
			this.EmailEntry.InvisibleChar = '●';
			this.hbox23.Add (this.EmailEntry);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.EmailEntry]));
			w27.Position = 1;
			w27.Padding = ((uint)(3));
			this.vbox12.Add (this.hbox23);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox23]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.vbox6.Add (this.fixed6);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.fixed6]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox12.Add (this.vbox6);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox6]));
			w30.Position = 2;
			this.vbox10.Add (this.vbox12);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox12]));
			w31.Position = 2;
			this.vbox8.Add (this.vbox10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox10]));
			w32.Position = 1;
			this.GtkAlignment.Add (this.vbox8);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Datos generales</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.hbox7.Add (this.frame1);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.frame1]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox6.Add (this.hbox7);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.hbox7]));
			w36.Position = 0;
			this.vbox2.Add (this.hbox6);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox6]));
			w37.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.EditButton = new global::Gtk.Button ();
			this.EditButton.CanFocus = true;
			this.EditButton.Name = "EditButton";
			this.EditButton.UseUnderline = true;
			this.EditButton.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.hbox15.Add (this.EditButton);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.EditButton]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.DeleteButton = new global::Gtk.Button ();
			this.DeleteButton.CanFocus = true;
			this.DeleteButton.Name = "DeleteButton";
			this.DeleteButton.UseUnderline = true;
			this.DeleteButton.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox15.Add (this.DeleteButton);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.DeleteButton]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.hbox15.Add (this.fixed3);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.fixed3]));
			w40.Position = 2;
			// Container child hbox15.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox ();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.OkButton = new global::Gtk.Button ();
			this.OkButton.CanFocus = true;
			this.OkButton.Name = "OkButton";
			this.OkButton.UseUnderline = true;
			this.OkButton.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hbox16.Add (this.OkButton);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.OkButton]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox16.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox16.Add (this.CancelButton);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.CancelButton]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.hbox15.Add (this.hbox16);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.hbox16]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox2.Add (this.hbox15);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox15]));
			w44.PackType = ((global::Gtk.PackType)(1));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 529;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
