
// This file has been generated by the GUI designer. Do not modify.
namespace omarkhd.Gymk
{
	public partial class PacksWindow
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox24;

		private global::Gtk.VBox vbox7;

		private global::Gtk.HSeparator hseparator2;

		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label1;

		private global::Gtk.Entry NameEntry;

		private global::Gtk.Button AreasButton;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label6;

		private global::Gtk.VBox SpinBox1;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label7;

		private global::Gtk.VBox SpinBox2;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Fixed fixed10;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Button OkButton;

		private global::Gtk.Button CancelButton;

		private global::Gtk.VBox vbox9;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView PacksNodeView;

		private global::Gtk.HBox hbox8;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Fixed fixed8;

		private global::Gtk.Button DeleteButton;

		private global::Gtk.Button EditButton;

		private global::Gtk.Button AddButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget omarkhd.Gymk.PacksWindow
			this.Name = "omarkhd.Gymk.PacksWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Paquetes de cobro");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child omarkhd.Gymk.PacksWindow.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.vbox6.Add (this.fixed6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.fixed6]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 290;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Paquetes que se usarán en la inscripción de miembros al gimnasio, por ejemplo: es" + "tudiantes, tercera edad, general, etc.");
			this.label4.Wrap = true;
			this.vbox6.Add (this.label4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox ();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox7.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hseparator2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre: ");
			this.hbox4.Add (this.label1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.NameEntry = new global::Gtk.Entry ();
			this.NameEntry.WidthRequest = 62;
			this.NameEntry.CanFocus = true;
			this.NameEntry.Name = "NameEntry";
			this.NameEntry.IsEditable = true;
			this.NameEntry.InvisibleChar = '•';
			this.hbox4.Add (this.NameEntry);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.NameEntry]));
			w5.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.AreasButton = new global::Gtk.Button ();
			this.AreasButton.CanFocus = true;
			this.AreasButton.Name = "AreasButton";
			this.AreasButton.UseUnderline = true;
			this.AreasButton.Label = global::Mono.Unix.Catalog.GetString ("Áreas...");
			this.hbox4.Add (this.AreasButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.AreasButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox8.Add (this.hbox4);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox4]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.WidthRequest = 90;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Mensualidad: $");
			this.label6.Wrap = true;
			this.hbox5.Add (this.label6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label6]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.SpinBox1 = new global::Gtk.VBox ();
			this.SpinBox1.Name = "SpinBox1";
			this.SpinBox1.Spacing = 6;
			this.hbox5.Add (this.SpinBox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.SpinBox1]));
			w9.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.WidthRequest = 74;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Inscripción: $");
			this.label7.Wrap = true;
			this.hbox6.Add (this.label7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label7]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.SpinBox2 = new global::Gtk.VBox ();
			this.SpinBox2.Name = "SpinBox2";
			this.SpinBox2.Spacing = 6;
			this.hbox6.Add (this.SpinBox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.SpinBox2]));
			w11.Position = 1;
			this.hbox5.Add (this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.hbox6]));
			w12.Position = 2;
			this.vbox8.Add (this.hbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.hbox7.Add (this.fixed10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.fixed10]));
			w14.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.OkButton = new global::Gtk.Button ();
			this.OkButton.CanFocus = true;
			this.OkButton.Name = "OkButton";
			this.OkButton.UseUnderline = true;
			this.OkButton.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hbox10.Add (this.OkButton);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.OkButton]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox10.Add (this.CancelButton);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.CancelButton]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			this.hbox7.Add (this.hbox10);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.hbox10]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.vbox8.Add (this.hbox7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.vbox7.Add (this.vbox8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.PacksNodeView = new global::Gtk.NodeView ();
			this.PacksNodeView.CanFocus = true;
			this.PacksNodeView.Name = "PacksNodeView";
			this.PacksNodeView.Reorderable = true;
			this.GtkScrolledWindow.Add (this.PacksNodeView);
			this.vbox9.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.GtkScrolledWindow]));
			w21.Position = 0;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed ();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.hbox9.Add (this.fixed8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed8]));
			w22.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.DeleteButton = new global::Gtk.Button ();
			this.DeleteButton.CanFocus = true;
			this.DeleteButton.Name = "DeleteButton";
			this.DeleteButton.UseUnderline = true;
			this.DeleteButton.Label = global::Mono.Unix.Catalog.GetString ("Eliminar");
			this.hbox9.Add (this.DeleteButton);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.DeleteButton]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.hbox8.Add (this.hbox9);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.hbox9]));
			w24.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.EditButton = new global::Gtk.Button ();
			this.EditButton.CanFocus = true;
			this.EditButton.Name = "EditButton";
			this.EditButton.UseUnderline = true;
			this.EditButton.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.hbox8.Add (this.EditButton);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.EditButton]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.AddButton = new global::Gtk.Button ();
			this.AddButton.CanFocus = true;
			this.AddButton.Name = "AddButton";
			this.AddButton.UseUnderline = true;
			this.AddButton.Label = global::Mono.Unix.Catalog.GetString ("Añadir");
			this.hbox8.Add (this.AddButton);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.AddButton]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox9.Add (this.hbox8);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox8]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			w27.Padding = ((uint)(2));
			this.vbox7.Add (this.vbox9);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox9]));
			w28.Position = 2;
			this.hbox24.Add (this.vbox7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.vbox7]));
			w29.Position = 0;
			w29.Padding = ((uint)(4));
			this.vbox6.Add (this.hbox24);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox24]));
			w30.Position = 2;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 346;
			this.DefaultHeight = 390;
			this.Show ();
		}
	}
}
