
// This file has been generated by the GUI designer. Do not modify.
namespace omarkhd.Gymk
{
	public partial class SelectAreasWindow
	{
		private global::Gtk.VBox vbox12;

		private global::Gtk.Fixed fixed11;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView AreasTreeView;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Fixed fixed12;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Button OkButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget omarkhd.Gymk.SelectAreasWindow
			this.WidthRequest = 200;
			this.HeightRequest = 250;
			this.Name = "omarkhd.Gymk.SelectAreasWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Seleccione");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(1));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child omarkhd.Gymk.SelectAreasWindow.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.vbox12.Add (this.fixed11);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.fixed11]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.AreasTreeView = new global::Gtk.TreeView ();
			this.AreasTreeView.CanFocus = true;
			this.AreasTreeView.Name = "AreasTreeView";
			this.GtkScrolledWindow.Add (this.AreasTreeView);
			this.vbox12.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.GtkScrolledWindow]));
			w3.Position = 1;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed ();
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			this.hbox11.Add (this.fixed12);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.fixed12]));
			w4.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.hbox11.Add (this.fixed1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.fixed1]));
			w5.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.OkButton = new global::Gtk.Button ();
			this.OkButton.CanFocus = true;
			this.OkButton.Name = "OkButton";
			this.OkButton.UseUnderline = true;
			this.OkButton.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hbox11.Add (this.OkButton);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.OkButton]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox12.Add (this.hbox11);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox11]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w7.Padding = ((uint)(2));
			this.Add (this.vbox12);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 208;
			this.DefaultHeight = 276;
			this.Show ();
		}
	}
}
