
// This file has been generated by the GUI designer. Do not modify.
namespace omarkhd.Gymk
{
	public partial class ConfigWindow
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.Fixed fixed1;

		private global::Gtk.Notebook notebook1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.VBox vbox5;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button LogoButton;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Fixed fixed7;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Entry GymNameEntry;

		private global::Gtk.Label label7;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Entry GymAddressEntry;

		private global::Gtk.Label label8;

		private global::Gtk.Entry GymPhoneEntry;

		private global::Gtk.Label GtkLabel8;

		private global::Gtk.Frame frame2;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Fixed fixed8;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label9;

		private global::Gtk.Entry OwnerNameEntry;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label10;

		private global::Gtk.Entry OwnerPhoneEntry;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label11;

		private global::Gtk.Entry OwnerEmailEntry;

		private global::Gtk.Label GtkLabel9;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Fixed fixed9;

		private global::Gtk.Fixed fixed10;

		private global::Gtk.Button SaveGralButton;

		private global::Gtk.Button Close1Button;

		private global::Gtk.Label label1;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Fixed fixed3;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Frame frame3;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Fixed fixed11;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label12;

		private global::Gtk.SpinButton DelayChargeSpin;

		private global::Gtk.VBox vbox17;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Label label13;

		private global::Gtk.CheckButton SaturdayCheck;

		private global::Gtk.CheckButton SundayCheck;

		private global::Gtk.Label GtkLabel12;

		private global::Gtk.HBox hbox15;

		private global::Gtk.Fixed fixed12;

		private global::Gtk.Fixed fixed13;

		private global::Gtk.Button SavePaymentButton;

		private global::Gtk.Button Close2Button;

		private global::Gtk.Label label2;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.VBox vbox6;

		private global::Gtk.HBox hbox4;

		private global::Gtk.VBox vbox7;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView UsersNodeView;

		private global::Gtk.Button AddButton;

		private global::Gtk.Button EditButton;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Button CancelButton;

		private global::Gtk.Button OkButton;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Fixed fixed6;

		private global::Gtk.HBox hbox12;

		private global::Gtk.CheckButton AdminCheckBox;

		private global::Gtk.CheckButton ActiveCheckBox;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label4;

		private global::Gtk.Entry AliasEntry;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label5;

		private global::Gtk.Entry NameEntry;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Button PasswordButton;

		private global::Gtk.Button AccessButton;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Fixed fixed5;

		private global::Gtk.Label label3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget omarkhd.Gymk.ConfigWindow
			this.Name = "omarkhd.Gymk.ConfigWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Preferencias");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child omarkhd.Gymk.ConfigWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			this.vbox1.Add (this.fixed1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.fixed1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(6));
			// Container child vbox2.Gtk.Box+BoxChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			this.vbox2.Add (this.fixed2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.fixed2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LogoButton = new global::Gtk.Button ();
			this.LogoButton.WidthRequest = 180;
			this.LogoButton.HeightRequest = 180;
			this.LogoButton.CanFocus = true;
			this.LogoButton.Name = "LogoButton";
			this.LogoButton.UseUnderline = true;
			this.LogoButton.Label = global::Mono.Unix.Catalog.GetString ("(seleccionar logo)\r\n");
			this.hbox2.Add (this.LogoButton);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.LogoButton]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox ();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.fixed7 = new global::Gtk.Fixed ();
			this.fixed7.Name = "fixed7";
			this.fixed7.HasWindow = false;
			this.vbox11.Add (this.fixed7);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.fixed7]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0f;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre:");
			this.vbox11.Add (this.label6);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.label6]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.GymNameEntry = new global::Gtk.Entry ();
			this.GymNameEntry.CanFocus = true;
			this.GymNameEntry.Name = "GymNameEntry";
			this.GymNameEntry.IsEditable = true;
			this.GymNameEntry.InvisibleChar = '●';
			this.vbox12.Add (this.GymNameEntry);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.GymNameEntry]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0f;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Dirección:");
			this.vbox12.Add (this.label7);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label7]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.GymAddressEntry = new global::Gtk.Entry ();
			this.GymAddressEntry.CanFocus = true;
			this.GymAddressEntry.Name = "GymAddressEntry";
			this.GymAddressEntry.IsEditable = true;
			this.GymAddressEntry.InvisibleChar = '●';
			this.vbox13.Add (this.GymAddressEntry);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.GymAddressEntry]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 0f;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Teléfono:");
			this.vbox13.Add (this.label8);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.label8]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.GymPhoneEntry = new global::Gtk.Entry ();
			this.GymPhoneEntry.CanFocus = true;
			this.GymPhoneEntry.Name = "GymPhoneEntry";
			this.GymPhoneEntry.IsEditable = true;
			this.GymPhoneEntry.InvisibleChar = '●';
			this.vbox13.Add (this.GymPhoneEntry);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.GymPhoneEntry]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox12.Add (this.vbox13);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox11.Add (this.vbox12);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.vbox12]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.GtkAlignment.Add (this.vbox11);
			this.frame1.Add (this.GtkAlignment);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Gimnasio</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel8;
			this.hbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame1]));
			w15.Position = 1;
			this.vbox5.Add (this.hbox2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox2]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox ();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.fixed8 = new global::Gtk.Fixed ();
			this.fixed8.Name = "fixed8";
			this.fixed8.HasWindow = false;
			this.vbox14.Add (this.fixed8);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.fixed8]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.WidthRequest = 120;
			this.label9.Name = "label9";
			this.label9.Xalign = 0f;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre completo");
			this.hbox3.Add (this.label9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label9]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.OwnerNameEntry = new global::Gtk.Entry ();
			this.OwnerNameEntry.CanFocus = true;
			this.OwnerNameEntry.Name = "OwnerNameEntry";
			this.OwnerNameEntry.IsEditable = true;
			this.OwnerNameEntry.InvisibleChar = '●';
			this.hbox3.Add (this.OwnerNameEntry);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.OwnerNameEntry]));
			w19.Position = 1;
			this.vbox14.Add (this.hbox3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox3]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.WidthRequest = 120;
			this.label10.Name = "label10";
			this.label10.Xalign = 0f;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Contacto (teléfono)");
			this.hbox5.Add (this.label10);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label10]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.OwnerPhoneEntry = new global::Gtk.Entry ();
			this.OwnerPhoneEntry.CanFocus = true;
			this.OwnerPhoneEntry.Name = "OwnerPhoneEntry";
			this.OwnerPhoneEntry.IsEditable = true;
			this.OwnerPhoneEntry.InvisibleChar = '●';
			this.hbox5.Add (this.OwnerPhoneEntry);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.OwnerPhoneEntry]));
			w22.Position = 1;
			this.vbox14.Add (this.hbox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox5]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.WidthRequest = 120;
			this.label11.Name = "label11";
			this.label11.Xalign = 0f;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Contacto (e-mail)");
			this.hbox6.Add (this.label11);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label11]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.OwnerEmailEntry = new global::Gtk.Entry ();
			this.OwnerEmailEntry.CanFocus = true;
			this.OwnerEmailEntry.Name = "OwnerEmailEntry";
			this.OwnerEmailEntry.IsEditable = true;
			this.OwnerEmailEntry.InvisibleChar = '●';
			this.hbox6.Add (this.OwnerEmailEntry);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.OwnerEmailEntry]));
			w25.Position = 1;
			this.vbox14.Add (this.hbox6);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox6]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment1.Add (this.vbox14);
			this.frame2.Add (this.GtkAlignment1);
			this.GtkLabel9 = new global::Gtk.Label ();
			this.GtkLabel9.Name = "GtkLabel9";
			this.GtkLabel9.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Dueño</b>");
			this.GtkLabel9.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel9;
			this.vbox5.Add (this.frame2);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.frame2]));
			w29.Position = 1;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed9 = new global::Gtk.Fixed ();
			this.fixed9.Name = "fixed9";
			this.fixed9.HasWindow = false;
			this.hbox9.Add (this.fixed9);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed9]));
			w30.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.fixed10 = new global::Gtk.Fixed ();
			this.fixed10.Name = "fixed10";
			this.fixed10.HasWindow = false;
			this.hbox9.Add (this.fixed10);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.fixed10]));
			w31.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.SaveGralButton = new global::Gtk.Button ();
			this.SaveGralButton.CanFocus = true;
			this.SaveGralButton.Name = "SaveGralButton";
			this.SaveGralButton.UseUnderline = true;
			this.SaveGralButton.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.hbox9.Add (this.SaveGralButton);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.SaveGralButton]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.Close1Button = new global::Gtk.Button ();
			this.Close1Button.CanFocus = true;
			this.Close1Button.Name = "Close1Button";
			this.Close1Button.UseUnderline = true;
			this.Close1Button.Label = global::Mono.Unix.Catalog.GetString ("Cerrar");
			this.hbox9.Add (this.Close1Button);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.Close1Button]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox5.Add (this.hbox9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox5]));
			w35.Position = 1;
			this.notebook1.Add (this.vbox2);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("General");
			this.notebook1.SetTabLabel (this.vbox2, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.fixed3 = new global::Gtk.Fixed ();
			this.fixed3.Name = "fixed3";
			this.fixed3.HasWindow = false;
			this.vbox3.Add (this.fixed3);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.fixed3]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox ();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			this.vbox15.BorderWidth = ((uint)(6));
			// Container child vbox15.Gtk.Box+BoxChild
			this.frame3 = new global::Gtk.Frame ();
			this.frame3.Name = "frame3";
			this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame3.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox16 = new global::Gtk.VBox ();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.fixed11 = new global::Gtk.Fixed ();
			this.fixed11.Name = "fixed11";
			this.fixed11.HasWindow = false;
			this.vbox16.Add (this.fixed11);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.fixed11]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.WidthRequest = 180;
			this.label12.Name = "label12";
			this.label12.Xalign = 0f;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Cargo de atraso ($ por día)");
			this.hbox10.Add (this.label12);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label12]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.DelayChargeSpin = new global::Gtk.SpinButton (0, 1000, 0.01);
			this.DelayChargeSpin.CanFocus = true;
			this.DelayChargeSpin.Name = "DelayChargeSpin";
			this.DelayChargeSpin.Adjustment.PageIncrement = 1;
			this.DelayChargeSpin.ClimbRate = 1;
			this.DelayChargeSpin.Numeric = true;
			this.hbox10.Add (this.DelayChargeSpin);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.DelayChargeSpin]));
			w40.Position = 1;
			this.vbox16.Add (this.hbox10);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox10]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox ();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.WidthRequest = 180;
			this.label13.Name = "label13";
			this.label13.Xalign = 0f;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Cobrar atrasos de");
			this.hbox14.Add (this.label13);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.label13]));
			w42.Position = 0;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.SaturdayCheck = new global::Gtk.CheckButton ();
			this.SaturdayCheck.CanFocus = true;
			this.SaturdayCheck.Name = "SaturdayCheck";
			this.SaturdayCheck.Label = global::Mono.Unix.Catalog.GetString ("Sábado");
			this.SaturdayCheck.DrawIndicator = true;
			this.SaturdayCheck.UseUnderline = true;
			this.hbox14.Add (this.SaturdayCheck);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.SaturdayCheck]));
			w43.Position = 1;
			// Container child hbox14.Gtk.Box+BoxChild
			this.SundayCheck = new global::Gtk.CheckButton ();
			this.SundayCheck.CanFocus = true;
			this.SundayCheck.Name = "SundayCheck";
			this.SundayCheck.Label = global::Mono.Unix.Catalog.GetString ("Domingo");
			this.SundayCheck.DrawIndicator = true;
			this.SundayCheck.UseUnderline = true;
			this.hbox14.Add (this.SundayCheck);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.SundayCheck]));
			w44.Position = 2;
			this.vbox17.Add (this.hbox14);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.hbox14]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			this.vbox16.Add (this.vbox17);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.vbox17]));
			w46.Position = 2;
			this.GtkAlignment2.Add (this.vbox16);
			this.frame3.Add (this.GtkAlignment2);
			this.GtkLabel12 = new global::Gtk.Label ();
			this.GtkLabel12.Name = "GtkLabel12";
			this.GtkLabel12.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Retrasos</b>");
			this.GtkLabel12.UseMarkup = true;
			this.frame3.LabelWidget = this.GtkLabel12;
			this.vbox15.Add (this.frame3);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.frame3]));
			w49.Position = 0;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.fixed12 = new global::Gtk.Fixed ();
			this.fixed12.Name = "fixed12";
			this.fixed12.HasWindow = false;
			this.hbox15.Add (this.fixed12);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.fixed12]));
			w50.Position = 0;
			// Container child hbox15.Gtk.Box+BoxChild
			this.fixed13 = new global::Gtk.Fixed ();
			this.fixed13.Name = "fixed13";
			this.fixed13.HasWindow = false;
			this.hbox15.Add (this.fixed13);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.fixed13]));
			w51.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.SavePaymentButton = new global::Gtk.Button ();
			this.SavePaymentButton.CanFocus = true;
			this.SavePaymentButton.Name = "SavePaymentButton";
			this.SavePaymentButton.UseUnderline = true;
			this.SavePaymentButton.Label = global::Mono.Unix.Catalog.GetString ("Guardar");
			this.hbox15.Add (this.SavePaymentButton);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.SavePaymentButton]));
			w52.Position = 2;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.Close2Button = new global::Gtk.Button ();
			this.Close2Button.CanFocus = true;
			this.Close2Button.Name = "Close2Button";
			this.Close2Button.UseUnderline = true;
			this.Close2Button.Label = global::Mono.Unix.Catalog.GetString ("Cerrar");
			this.hbox15.Add (this.Close2Button);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox15[this.Close2Button]));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			this.vbox15.Add (this.hbox15);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox15]));
			w54.Position = 2;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox3.Add (this.vbox15);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox15]));
			w55.Position = 1;
			this.notebook1.Add (this.vbox3);
			global::Gtk.Notebook.NotebookChild w56 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox3]));
			w56.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Pagos");
			this.notebook1.SetTabLabel (this.vbox3, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed ();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			this.vbox4.Add (this.fixed4);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.fixed4]));
			w57.Position = 0;
			w57.Expand = false;
			w57.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(7));
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 160;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.UsersNodeView = new global::Gtk.NodeView ();
			this.UsersNodeView.CanFocus = true;
			this.UsersNodeView.Name = "UsersNodeView";
			this.GtkScrolledWindow.Add (this.UsersNodeView);
			this.vbox7.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.GtkScrolledWindow]));
			w59.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.AddButton = new global::Gtk.Button ();
			this.AddButton.CanFocus = true;
			this.AddButton.Name = "AddButton";
			this.AddButton.UseUnderline = true;
			this.AddButton.Label = global::Mono.Unix.Catalog.GetString ("Añadir");
			this.vbox7.Add (this.AddButton);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.AddButton]));
			w60.Position = 1;
			w60.Expand = false;
			w60.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.EditButton = new global::Gtk.Button ();
			this.EditButton.CanFocus = true;
			this.EditButton.Name = "EditButton";
			this.EditButton.UseUnderline = true;
			this.EditButton.Label = global::Mono.Unix.Catalog.GetString ("Editar");
			this.vbox7.Add (this.EditButton);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.EditButton]));
			w61.Position = 2;
			w61.Expand = false;
			w61.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.CancelButton = new global::Gtk.Button ();
			this.CancelButton.CanFocus = true;
			this.CancelButton.Name = "CancelButton";
			this.CancelButton.UseUnderline = true;
			this.CancelButton.Label = global::Mono.Unix.Catalog.GetString ("Cancelar");
			this.hbox13.Add (this.CancelButton);
			global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.CancelButton]));
			w62.Position = 0;
			// Container child hbox13.Gtk.Box+BoxChild
			this.OkButton = new global::Gtk.Button ();
			this.OkButton.CanFocus = true;
			this.OkButton.Name = "OkButton";
			this.OkButton.UseUnderline = true;
			this.OkButton.Label = global::Mono.Unix.Catalog.GetString ("Ok");
			this.hbox13.Add (this.OkButton);
			global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.OkButton]));
			w63.Position = 1;
			this.vbox7.Add (this.hbox13);
			global::Gtk.Box.BoxChild w64 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox13]));
			w64.Position = 3;
			w64.Expand = false;
			w64.Fill = false;
			this.hbox4.Add (this.vbox7);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox7]));
			w65.Position = 0;
			w65.Expand = false;
			w65.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			this.vbox8.BorderWidth = ((uint)(6));
			// Container child vbox8.Gtk.Box+BoxChild
			this.fixed6 = new global::Gtk.Fixed ();
			this.fixed6.Name = "fixed6";
			this.fixed6.HasWindow = false;
			this.vbox8.Add (this.fixed6);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.fixed6]));
			w66.Position = 0;
			w66.Expand = false;
			w66.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.AdminCheckBox = new global::Gtk.CheckButton ();
			this.AdminCheckBox.CanFocus = true;
			this.AdminCheckBox.Name = "AdminCheckBox";
			this.AdminCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Administrador");
			this.AdminCheckBox.DrawIndicator = true;
			this.AdminCheckBox.UseUnderline = true;
			this.hbox12.Add (this.AdminCheckBox);
			global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.AdminCheckBox]));
			w67.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.ActiveCheckBox = new global::Gtk.CheckButton ();
			this.ActiveCheckBox.CanFocus = true;
			this.ActiveCheckBox.Name = "ActiveCheckBox";
			this.ActiveCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Activo");
			this.ActiveCheckBox.DrawIndicator = true;
			this.ActiveCheckBox.UseUnderline = true;
			this.hbox12.Add (this.ActiveCheckBox);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.ActiveCheckBox]));
			w68.Position = 1;
			this.vbox8.Add (this.hbox12);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox12]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.WidthRequest = 50;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuario");
			this.label4.Wrap = true;
			this.hbox7.Add (this.label4);
			global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label4]));
			w70.Position = 0;
			w70.Expand = false;
			w70.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.AliasEntry = new global::Gtk.Entry ();
			this.AliasEntry.CanFocus = true;
			this.AliasEntry.Name = "AliasEntry";
			this.AliasEntry.IsEditable = true;
			this.AliasEntry.InvisibleChar = '●';
			this.hbox7.Add (this.AliasEntry);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.AliasEntry]));
			w71.Position = 1;
			this.vbox8.Add (this.hbox7);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
			w72.Position = 2;
			w72.Expand = false;
			w72.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.WidthRequest = 50;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.label5.Wrap = true;
			this.hbox8.Add (this.label5);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label5]));
			w73.Position = 0;
			w73.Expand = false;
			w73.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.NameEntry = new global::Gtk.Entry ();
			this.NameEntry.CanFocus = true;
			this.NameEntry.Name = "NameEntry";
			this.NameEntry.IsEditable = true;
			this.NameEntry.InvisibleChar = '●';
			this.hbox8.Add (this.NameEntry);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.NameEntry]));
			w74.Position = 1;
			this.vbox9.Add (this.hbox8);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox8]));
			w75.Position = 0;
			w75.Expand = false;
			w75.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.PasswordButton = new global::Gtk.Button ();
			this.PasswordButton.CanFocus = true;
			this.PasswordButton.Name = "PasswordButton";
			this.PasswordButton.UseUnderline = true;
			this.PasswordButton.Label = global::Mono.Unix.Catalog.GetString ("Cambiar contraseña...");
			this.hbox11.Add (this.PasswordButton);
			global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.PasswordButton]));
			w76.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.AccessButton = new global::Gtk.Button ();
			this.AccessButton.CanFocus = true;
			this.AccessButton.Name = "AccessButton";
			this.AccessButton.UseUnderline = true;
			this.AccessButton.Label = global::Mono.Unix.Catalog.GetString ("Permisos...");
			this.hbox11.Add (this.AccessButton);
			global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.AccessButton]));
			w77.Position = 1;
			this.vbox9.Add (this.hbox11);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
			w78.Position = 1;
			w78.Expand = false;
			w78.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox9.Add (this.vbox10);
			global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vbox10]));
			w79.Position = 2;
			this.vbox8.Add (this.vbox9);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
			w80.Position = 3;
			this.hbox4.Add (this.vbox8);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.vbox8]));
			w81.Position = 1;
			w81.Expand = false;
			w81.Fill = false;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox4]));
			w82.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.fixed5 = new global::Gtk.Fixed ();
			this.fixed5.Name = "fixed5";
			this.fixed5.HasWindow = false;
			this.vbox6.Add (this.fixed5);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.fixed5]));
			w83.Position = 1;
			w83.Expand = false;
			w83.Fill = false;
			this.vbox4.Add (this.vbox6);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox6]));
			w84.Position = 1;
			this.notebook1.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w85 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.vbox4]));
			w85.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Usuarios");
			this.notebook1.SetTabLabel (this.vbox4, this.label3);
			this.label3.ShowAll ();
			this.vbox1.Add (this.notebook1);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.notebook1]));
			w86.Position = 1;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 423;
			this.Show ();
		}
	}
}
